{
 "title": "Scheduler Internal",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Scheduler Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_yt_alloc_total_bytes_used|yt_memory_generic_bytes_in_use_by_app\"}"
    }
   ]
  },
  {
   "title": "Controller Agent Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service=~\"yt-controller-agent\", __name__=~\"yt_yt_alloc_total_bytes_used|yt_memory_generic_bytes_in_use_by_app\"}"
    }
   ]
  },
  {
   "title": "Scheduler Control CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_resource_tracker_user_cpu\", thread=~\"Control\"}"
    }
   ]
  },
  {
   "title": "Controller Agent Control CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "{service=~\"yt-controller-agent\", __name__=~\"yt_resource_tracker_user_cpu\", thread=~\"Control\"}"
    }
   ]
  },
  {
   "title": "Scheduler Node Shards CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_resource_tracker_user_cpu\", thread=~\"NodeShard\"}"
    }
   ]
  },
  {
   "title": "Controller Agent Controllers CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{service=~\"yt-controller-agent\", __name__=~\"yt_resource_tracker_user_cpu\", thread=~\"Controller\"}"
    }
   ]
  },
  {
   "title": "Scheduler RPC Heavy CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_resource_tracker_user_cpu\", thread=~\"RpcHeavy\"}"
    }
   ]
  },
  {
   "title": "Controller Agent RPC Heavy CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "{service=~\"yt-controller-agent\", __name__=~\"yt_resource_tracker_user_cpu\", thread=~\"RpcHeavy\"}"
    }
   ]
  },
  {
   "title": "Scheduler Thread Pools CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_resource_tracker_user_cpu\", thread=~\"FSUpdatePool|OrchidWorker|Background\"}"
    }
   ]
  },
  {
   "title": "Control Thread Buckets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate({service=~\"yt-scheduler\", __name__=~\"yt_action_queue_time_cumulative\", bucket=~\".+\", thread=~\"Control\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Operation Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_running_operation_count|yt_scheduler_pools_total_operation_count\", pool=~\"<Root>\", tree=~\"default\"}"
    }
   ]
  },
  {
   "title": "Schedulable Element Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_schedulable_element_count\", pool=~\"<Root>\", tree=~\".+\"}"
    }
   ]
  },
  {
   "title": "Schedule job attempts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate({service=~\"yt-scheduler\", __name__=~\"yt_scheduler_schedule_job_attempt_count\", schedule_jobs_stage=~\"\", scheduling_stage=~\"\", tree=~\".+\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Preschedule job count rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate({service=~\"yt-scheduler\", __name__=~\"yt_scheduler_preschedule_job_count\", schedule_jobs_stage=~\"\", scheduling_stage=~\"\", tree=~\".+\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Preemptive preschedule job attempts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate({service=~\"yt-scheduler\", __name__=~\"yt_scheduler_preschedule_job_count\", scheduling_stage!~\"non_preemptive|^$\", tree=~\"default\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Aborted vs completed job time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "rate({service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_metrics_total_time_aborted_rate|yt_scheduler_pools_metrics_total_time_completed\", pool=~\"<Root>\", tree=~\"default\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Aborted jobs rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate({service=~\"yt-controller-agent\", __name__=~\"yt_controller_agent_jobs_aborted_job_count\", abort_reason!~\"preemption|^$\", job_type=~\"\", tree=~\"\"}[$__rate_interval])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Scheduler Logging",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "rate({service=~\"yt-scheduler\", __name__=~\"yt_logging_enqueued_events_rate|yt_logging_dropped_events\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Controller Agent Logging",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "rate({service=~\"yt-controller-agent\", __name__=~\"yt_logging_enqueued_events\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "AllocationTrackerService.Heartbeat rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "rate({service=~\"yt-scheduler\", __name__=~\"yt_rpc_server_request_count\", user=~\"\", yt_service=~\"JobTrackerService|AllocationTrackerService\", method=~\"Heartbeat\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "AllocationTrackerService.Heartbeat queue size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_rpc_server_request_queue_size\", user=~\"\", yt_service=~\"JobTrackerService|AllocationTrackerService\", method=~\"Heartbeat\"}"
    }
   ]
  },
  {
   "title": "AllocationTrackerService.Heartbeat time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_rpc_server_request_time_total_max\", user=~\"\", yt_service=~\"JobTrackerService|AllocationTrackerService\", method=~\"Heartbeat\"}"
    }
   ]
  },
  {
   "title": "AllocationTrackerService.Heartbeat concurrency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_rpc_server_concurrency.*\", user=~\"\", yt_service=~\"JobTrackerService|AllocationTrackerService\", method=~\"Heartbeat\"}"
    }
   ]
  },
  {
   "title": "ControllerAgentTrackerService.Heartbeat rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "rate({service=~\"yt-scheduler\", __name__=~\"yt_rpc_server_request_count\", user=~\"\", yt_service=~\"ControllerAgentTrackerService\", method=~\".*Heartbeat\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "ControllerAgentTrackerService.Heartbeat time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_rpc_server_request_time_total_max\", user=~\"\", yt_service=~\"ControllerAgentTrackerService\", method=~\".*Heartbeat\"}"
    }
   ]
  },
  {
   "title": "JobSpecService.GetJobSpecs rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "rate({service=~\"yt-controller-agent\", __name__=~\"yt_rpc_server_request_count\", user=~\"\", yt_service=~\"JobSpecService\", method=~\"GetJobSpecs\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "JobSpecService.GetJobSpecs queue size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "{service=~\"yt-controller-agent\", __name__=~\"yt_rpc_server_request_queue_size\", user=~\"\", yt_service=~\"JobSpecService\", method=~\"GetJobSpecs\"}"
    }
   ]
  },
  {
   "title": "JobSpecService.GetJobSpecs time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "{service=~\"yt-controller-agent\", __name__=~\"yt_rpc_server_request_time_total_max\", user=~\"\", yt_service=~\"JobSpecService\", method=~\"GetJobSpecs\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {}
   ]
  }
 ]
}
{
 "title": "Scheduler Pool",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "tree", "query": "default" },
   { "name": "pool", "query": "<Root>" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_resource_usage_cpu\", pool=~\"$pool\", tree=~\"$tree\"}"
    },
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_resource_demand_cpu\", pool=~\"$pool\", tree=~\"$tree\"}"
    },
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_effective_strong_guarantee_resources_cpu\", pool=~\"$pool\", tree=~\"$tree\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_resource_usage_user_memory\", pool=~\"$pool\", tree=~\"$tree\"}"
    },
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_resource_demand_user_memory\", pool=~\"$pool\", tree=~\"$tree\"}"
    },
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_effective_strong_guarantee_resources_user_memory\", pool=~\"$pool\", tree=~\"$tree\"}"
    }
   ]
  },
  {
   "title": "GPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_resource_usage_gpu\", pool=~\"$pool\", tree=~\"$tree\"}"
    },
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_resource_demand_gpu\", pool=~\"$pool\", tree=~\"$tree\"}"
    },
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_effective_strong_guarantee_resources_gpu\", pool=~\"$pool\", tree=~\"$tree\"}"
    }
   ]
  },
  {
   "title": "Running operation count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_running_operation_count\", pool=~\"$pool\", tree=~\"$tree\"}"
    },
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_max_running_operation_count\", pool=~\"$pool\", tree=~\"$tree\"}"
    }
   ]
  },
  {
   "title": "Total operation count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_total_operation_count\", pool=~\"$pool\", tree=~\"$tree\"}"
    },
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_max_operation_count\", pool=~\"$pool\", tree=~\"$tree\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "options": {
    "content": "\n- **Demand**: amount of resources needed to run all waiting and running jobs in the pool.\n- **Usage**: model resource consumption of the pool from scheduler's point of view. Represents the number of resources that are reserved for operations in the pool. Actual resource consumption may differ.\n- **Strong guarantee**: amount of resources that is guaranteed for operations in the pool at any moment.\n- **Total operation count**: total number of operations in the pool, includes \"Running operation count\". The difference between \"Total operation count\" and \"Running operation count\" is the size of the queue of operations that are waiting to be started.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Resource shares: usage, demand, fair share",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_dominant_usage_share\", pool=~\"$pool\", tree=~\"$tree\"}"
    },
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_dominant_demand_share\", pool=~\"$pool\", tree=~\"$tree\"}"
    },
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_dominant_fair_share_total\", pool=~\"$pool\", tree=~\"$tree\"}"
    }
   ]
  },
  {
   "title": "Fair share: CPU, RAM, GPU components",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_fair_share_total_cpu\", pool=~\"$pool\", tree=~\"$tree\"}"
    },
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_fair_share_total_memory\", pool=~\"$pool\", tree=~\"$tree\"}"
    },
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_fair_share_total_gpu\", pool=~\"$pool\", tree=~\"$tree\"}"
    }
   ]
  },
  {
   "title": "Dominant fair share: strong, integral, weight proportional",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_dominant_fair_share_integral_guarantee\", pool=~\"$pool\", tree=~\"$tree\"}"
    },
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_dominant_fair_share_strong_guarantee\", pool=~\"$pool\", tree=~\"$tree\"}"
    },
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_dominant_fair_share_weight_proportional\", pool=~\"$pool\", tree=~\"$tree\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "options": {
    "content": "\n- **Usage**, **Demand**, **Fair share**: share of the cluster that is used, demanded or should be given to the pool. For example, 1.0 or 100% corresponds to the total amount of resources in the cluster.\n- **CPU. RAM, GPU fair share components**  help to determine pool's dominant resource.\n\nIn addition, fair share can be split into three parts: strong guarantee, integral guarantee and free resources, which are distributed between pools in proportion to their weights.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Job metrics: local disk IO",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate({service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_metrics_user_job_io_total\", pool=~\"$pool\", tree=~\"$tree\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Job metrics: CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "expr": "rate({service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_metrics_user_job_cpu_system\", pool=~\"$pool\", tree=~\"$tree\"}[$__rate_interval])"
    },
    {
     "expr": "rate({service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_metrics_user_job_cpu_user\", pool=~\"$pool\", tree=~\"$tree\"}[$__rate_interval])"
    },
    {
     "expr": "rate({service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_metrics_job_proxy_cpu_system\", pool=~\"$pool\", tree=~\"$tree\"}[$__rate_interval])"
    },
    {
     "expr": "rate({service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_metrics_job_proxy_cpu_user\", pool=~\"$pool\", tree=~\"$tree\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Job metrics: GPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "expr": "rate({service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_metrics_gpu_load\", pool=~\"$pool\", tree=~\"$tree\"}[$__rate_interval])"
    },
    {
     "expr": "rate({service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_metrics_gpu_utilization_gpu\", pool=~\"$pool\", tree=~\"$tree\"}[$__rate_interval])"
    },
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_resource_usage_gpu\", pool=~\"$pool\", tree=~\"$tree\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "options": {
    "content": "\n- **Local disk I/O**: total amount of input/output operations per second (IOPS) of all user jobs in the pool.\n- **CPU usage**: total detailed CPU usage statistics of all user jobs and their job proxies in the pool.\n- **GPU usage**: total detailed GPU utilization statistics of all user jobs in the pool.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Accumulated resource volume: CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_accumulated_resource_volume_cpu\", pool=~\"$pool\", tree=~\"$tree\"}"
    }
   ]
  },
  {
   "title": "Accumulated resource volume: RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_accumulated_resource_volume_user_memory\", pool=~\"$pool\", tree=~\"$tree\"}"
    }
   ]
  },
  {
   "title": "Accumulated resource volume share",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_accumulated_volume_dominant_share\", pool=~\"$pool\", tree=~\"$tree\"}"
    }
   ]
  },
  {
   "title": "Accepted free volume: CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_accepted_free_volume_cpu\", pool=~\"$pool\", tree=~\"$tree\"}"
    }
   ]
  },
  {
   "title": "Accepted free volume: RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 48 },
   "targets": [
    {
     "expr": "{service=~\"yt-scheduler\", __name__=~\"yt_scheduler_pools_accepted_free_volume_user_memory\", pool=~\"$pool\", tree=~\"$tree\"}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "options": {
    "content": "\nThe following metrics are only relevant for pools with burst or relaxed integral guarantees.\n\n- **Accumulated resource volume share**: amount of virtual resources accumulated in the pool which can be spent on integral guarantees. In `cluster_share*sec`.\n- **Accumulated resource volume (CPU/RAM)**: approximate amount of accumulated resources computed based on accumulated volume share and the current total resource amount in the cluster. In `cpu*sec`/`bytes*sec`.\n- **Accepted free volume (CPU/RAM)**: virtual resource volume which was obtained by the pool via redistribution of other pools' unused integral resource flows.\n"
   },
   "targets": [
    {}
   ]
  }
 ]
}
{
 "title": "Pool dashboard for UI",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster" },
   { "name": "pool_tree", "label": "Pool tree", "query": "default" },
   { "name": "pool", "label": "pool", "query": "research" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Usage, demand and strong guarantee"
   }
  },
  {
   "title": "CPU: usage, demand, guarantee",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=\"yt_scheduler_pools_resource_usage_cpu\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "{__name__=\"yt_scheduler_pools_resource_demand_cpu\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "demand"
    },
    {
     "expr": "{__name__=\"yt_scheduler_pools_strong_guarantee_resources_cpu\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "strong_guarantee"
    },
    {
     "expr": "{__name__=\"yt_scheduler_pools_specified_resource_limits_cpu\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "specified_limit"
    }
   ]
  },
  {
   "title": "RAM: usage, demand, guarantee",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=\"yt_scheduler_pools_resource_usage_user_memory\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "{__name__=\"yt_scheduler_pools_resource_demand_user_memory\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "demand"
    },
    {
     "expr": "{__name__=\"yt_scheduler_pools_strong_guarantee_resources_user_memory\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "strong_guarantee"
    },
    {
     "expr": "{__name__=\"yt_scheduler_pools_specified_resource_limits_user_memory\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "specified_limit"
    }
   ]
  },
  {
   "title": "GPU: usage, demand, guarantee",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=\"yt_scheduler_pools_resource_usage_gpu\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "{__name__=\"yt_scheduler_pools_resource_demand_gpu\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "demand"
    },
    {
     "expr": "{__name__=\"yt_scheduler_pools_strong_guarantee_resources_gpu\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "strong_guarantee"
    },
    {
     "expr": "{__name__=\"yt_scheduler_pools_specified_resource_limits_gpu\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "specified_limit"
    }
   ]
  },
  {
   "title": "Running operation count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=\"yt_scheduler_pools_running_operation_count\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "{__name__=\"yt_scheduler_pools_max_running_operation_count\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Total operation count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=\"yt_scheduler_pools_total_operation_count\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "{__name__=\"yt_scheduler_pools_max_operation_count\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "options": {
    "content": "<p>\n<br><b>Demand</b>: amount of resources needed to run all waiting and running jobs in the pool.\n<br><b>Usage</b>: model resource consumption of the pool from scheduler's point of view. Represents the number of resources that are reserved for operations in the pool. Actual resource consumption may differ.\n<br><b>Strong guarantee</b>: amount of resources that is guaranteed for operations in the pool at any moment.\n<br><b>Total operation count</b>: total number of operations in the pool, includes \"Running operation count\". The difference between \"Total operation count\" and \"Running operation count\" is the size of the queue of operations that are waiting to be started.\n</p>"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 }, "options": { "content": "# Cluster share" } },
  {
   "title": "Resource shares: usage, demand, fair share",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=\"yt_scheduler_pools_dominant_usage_share\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "dominant resource usage share"
    },
    {
     "expr": "{__name__=\"yt_scheduler_pools_dominant_demand_share\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "dominant resource demand share"
    },
    {
     "expr": "{__name__=\"yt_scheduler_pools_dominant_fair_share_total\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "dominant resource fair share"
    }
   ]
  },
  {
   "title": "Fair share: CPU, RAM, GPU components",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=\"yt_scheduler_pools_fair_share_total_cpu\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "cpu fair share"
    },
    {
     "expr": "{__name__=\"yt_scheduler_pools_fair_share_total_memory\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "memory fair share"
    },
    {
     "expr": "{__name__=\"yt_scheduler_pools_fair_share_total_gpu\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "gpu fair share"
    }
   ]
  },
  {
   "title": "Dominant fair share: strong, integral, weight proportional",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=\"yt_scheduler_pools_dominant_fair_share_integral_guarantee\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "integral guarantee"
    },
    {
     "expr": "{__name__=\"yt_scheduler_pools_dominant_fair_share_strong_guarantee\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "strong guarantee"
    },
    {
     "expr": "{__name__=\"yt_scheduler_pools_dominant_fair_share_weight_proportional\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "weight proportional"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 33 },
   "options": {
    "content": "<p>\n<br><b>Usage, Demand, Fair share</b>: share of the cluster that is used, demanded or should be given to the pool. For example, 1.0 or 100% corresponds to the total amount of resources in the cluster.\n<br><b>CPU. RAM, GPU fair share components</b> help to determine pool's dominant resource.\n</p>\n<p>\nIn addition, fair share can be split into three parts: strong guarantee, integral guarantee and free resources, which are distributed between pools in proportion to their weights.\n</p>"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 }, "options": { "content": "# Job Metrics" } },
  {
   "title": "Job metrics: local disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate({__name__=\"yt_scheduler_pools_metrics_user_job_io_total\", tree=\"$pool_tree\", pool=\"$pool\"}[$__rate_interval])",
     "legendFormat": "user job io rate"
    }
   ]
  },
  {
   "title": "Job metrics: CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate({__name__=\"yt_scheduler_pools_metrics_user_job_cpu_system\", tree=\"$pool_tree\", pool=\"$pool\"}[$__rate_interval])",
     "legendFormat": "user job system cpu rate"
    },
    {
     "expr": "rate({__name__=\"yt_scheduler_pools_metrics_user_job_cpu_user\", tree=\"$pool_tree\", pool=\"$pool\"}[$__rate_interval])",
     "legendFormat": "user job user cpu rate"
    },
    {
     "expr": "rate({__name__=\"yt_scheduler_pools_metrics_job_proxy_cpu_system\", tree=\"$pool_tree\", pool=\"$pool\"}[$__rate_interval])",
     "legendFormat": "job proxy system cpu rate"
    },
    {
     "expr": "rate({__name__=\"yt_scheduler_pools_metrics_job_proxy_cpu_user\", tree=\"$pool_tree\", pool=\"$pool\"}[$__rate_interval])",
     "legendFormat": "job proxy user cpu rate"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 48 },
   "options": {
    "content": "<p>\n<br><b>Local disk I/O</b>: total amount of input/output operations per second (IOPS) of all user jobs in the pool.\n<br><b>CPU usage</b>: total detailed CPU usage statistics of all user jobs and their job proxies in the pool.\n</p>\n<p>\nConsult documentation for more information on the corresponding job statistics.\n</p>"
   }
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 53 }, "options": { "content": "# Integral guarantee" } },
  {
   "title": "Accumulated resource volume: CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=\"yt_scheduler_pools_accumulated_resource_volume_cpu\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "accumulated cpu"
    }
   ]
  },
  {
   "title": "Accumulated resource volume: RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=\"yt_scheduler_pools_accumulated_resource_volume_user_memory\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "accumulated memory"
    }
   ]
  },
  {
   "title": "Accumulated resource volume share",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=\"yt_scheduler_pools_accumulated_volume_dominant_share\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "accumulated dominant resource share"
    }
   ]
  },
  {
   "title": "Accepted free volume: CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=\"yt_scheduler_pools_accepted_free_volume_cpu\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "accepted free cpu"
    }
   ]
  },
  {
   "title": "Accepted free volume: RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{__name__=\"yt_scheduler_pools_accepted_free_volume_user_memory\", tree=\"$pool_tree\", pool=\"$pool\"}",
     "legendFormat": "accepted free memory"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 71 },
   "options": {
    "content": "<p>\n  The following metrics are only relevant for pools with burst or relaxed integral guarantees.\n  <br><b>Accumulated resource volume share</b>: amount of virtual resources accumulated in the pool which can be spent on integral guarantees. In cluster_share*sec.\n  <br><b>Accumulated resource volume (CPU/RAM)</b>: approximate amount of accumulated resources computed based on accumulated volume share and the current total resource amount in the cluster. In cpu*sec/bytes*sec.\n  <br><b>Accepted free volume (CPU/RAM)</b>: virtual resource volume which was obtained by the pool via redistribution of other pools' unused integral resource flows.\n</p>\n<p>\n  Consult documentation for more information on intergral guarantees.\n</p>"
   }
  }
 ]
}
{
 "title": "YT Masters Internal",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster" }
  ]
 },
 "panels": [
  {
   "title": "Automaton Threads",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", __name__=\"yt_resource_tracker_user_cpu\", thread=\"Automaton\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Lost Vital Chunks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", __name__=\"yt_chunk_server_lost_vital_chunk_count\", cell_tag=~\".+\"}",
     "legendFormat": "{{cell_tag}}"
    }
   ]
  },
  {
   "title": "Data Missing Chunks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", __name__=\"yt_chunk_server_data_missing_chunk_count\", cell_tag=~\".+\"}",
     "legendFormat": "{{cell_tag}}"
    }
   ]
  },
  {
   "title": "Read Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate({cluster=\"$cluster\", __name__=\"yt_security_user_read_request_count\", user=\"root\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Parity Missing Chunks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", __name__=\"yt_chunk_server_parity_missing_chunk_count\", cell_tag=~\".+\"}",
     "legendFormat": "{{cell_tag}}"
    }
   ]
  },
  {
   "title": "Read Request Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate({cluster=\"$cluster\", __name__=\"yt_security_user_read_time\", user=\"root\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Underreplicated Chunks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "{cluster=\"$cluster\", __name__=\"yt_chunk_server_underreplicated_chunk_count\", cell_tag=~\".+\"}",
     "legendFormat": "{{cell_tag}}"
    }
   ]
  }
 ]
}